kio:
  default-pfp-key: kio-default-pfp
  oauth:
    client:
      id: kio
      secret: $2y$04$n8QZyDIWYdG8AF6EFCaa8Or4rib./RoMeSUo6kbxxBNKQETK/Uwve # secret in plain text
      access-token-validity-time: 15 # minutes
      refresh-token-validity-time: 7 # days

aws:
  s3:
    endpoint: http://127.0.0.1:4566
    files-bucket: files.kio.com
    profile-pictures-bucket: pfp.kio.com
    region: us-east-1
    access-key: localstack
    secret-key: localstack

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
      enabled: true

  data:
    mongodb:
      database: kio
      port: 27017
      host: localhost