kio:
  oauth:
    client:
      id: kio-oauth-client
      secret: 3xnWzGJE94qMWTvpp5mGeqsmFukwXR
      access-token-validity-time: 1200
      refresh-token-validity-time: 86400

aws:
  s3:
    endpoint: http://10.42.0.1:4566
    files-bucket: files.kio.com
    profile-pictures-bucket: pfp.kio.com
    region: us-east-1
    access-key: localstack
    secret-key: localstack

security:
  oauth2:
    resource:
      jwt-key-uri: http://localhost:8080/oauth/token-key
    client:
      client-id: rs
      client-secret: rssecret

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
      enabled: true
  data:
    mongodb:
      database: kio
      port: 27017
      host: localhost