kio:
  default-pfp-key: kio-default-pfp
  oauth:
    client:
      id: kio-oauth-client
      secret: 3xnWzGJE94qMWTvpp5mGeqsmFukwXR
      access-token-validity-time: 1200
      refresh-token-validity-time: 86400

aws:
  s3:
    endpoint: http://s3:4566
      files-bucket: files.kio.com
      profile-pictures-bucket: pfp.kio.com
      region: us-east-1
      access-key: localstack
      secret-key: localstack

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
      enabled: true

  #datasource:
  #  driver-class-name: org.postgresql.Driver
  #  username: glaze
  #  password: dalmatian
  #  url: jdbc:postgresql://postgres:5432/kio
  #jpa:
  #  hibernate:
  #    ddl-auto: create-drop
  #  show-sql: true
  #  database-platform: com.kio.configuration.pg.CustomDialect

  data:
    mongodb:
      database: kio
      port: 27017
      host: mongodb