kio:
  oauth:
    client:
      id: kio-oauth-client
      secret: 3xnWzGJE94qMWTvpp5mGeqsmFukwXR
      access-token-validity-time: 900
      refresh-token-validity-time: 604800
  store:
    folder: /home/glaze/Escritorio/store

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: glaze
    password: dalmatian
    url: jdbc:postgresql://localhost:5432/connect
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: com.kio.configuration.pg.CustomDialect
