version: "3.7"

services:
  localstack-s3:
    container_name: localstack-s3
    image: localstack/localstack:latest
    environment:
      DEBUG: 1
      USE_SSL: 0
      AWS_CBOR_DISABLE: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      HOSTNAME: localstack
      SERVICES: s3
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - /home/glaze/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-s3-bucket.sh:/docker-entrypoint-initaws.d/init-s3-bucket.sh