version: "3.7"

services:
#  kio:
#    container_name: kio
#    ports:
#      - '8080:8080'
#   depends_on:
#      - s3
#      - mongodb
#      - redis

  redis:
    image: redis:6.24-alpine
    container_name: redis
    port:
      - 6379:6379

  mongodb:
    image: mongodb:latest
    container_name: mongodb
    ports:
      - 27017:27017

  s3:
    image: localstack/localstack:latest
    container_name: s3
    environment:
      DEBUG: 1
      USE_SSL: 0
      AWS_CBOR_DISABLE: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      HOSTNAME: localstack
      SERVICES: s3
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - /home/glaze/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init-s3-bucket.sh:/docker-entrypoint-initaws.d/init-s3-bucket.sh